# Generated by Django 4.1.7 on 2023-05-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
